name: korea_social_login_example
description: Demonstrates how to use the korea_social_login plugin.
publish_to: 'none'

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  korea_social_login:
    path: ../
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.9

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
